repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - {id: trailing-whitespace, exclude: init_db/}
      - {id: end-of-file-fixer, exclude: init_db/}
      - {id: requirements-txt-fixer}
      - {
        id: no-commit-to-branch,
        args: ["--branch", main],
        exclude: init/db
      }